name: edu_platform
description: A Flutter educational platform app based on provided screenshots.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

  assets:
    # Add assets here if needed

# Enable internet permission for network images (AndroidManifest.xml needs to be updated separately)
